version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.2
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          key: deps9-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          name: Install Python deps in a venv
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt -c constraints.txt
            pip install .
      - save_cache:
          paths:
            - ./venv
          key: deps9-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          command: |
            . venv/bin/activate
            mkdir test-reports
            pytest --junitxml=test-reports/junit.xml
            pytest --cov=molehill --cov-report=term-missing --cov-report=html tests
            coverage html -d test-reports
      - store_test_results:
          path: test-reports

      - store_artifacts:
          path: test-reports
          destination: test-reports
